// web/src/features/settings/components/SettingsSidebar.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { Settings, Keyboard, Camera, Monitor, Menu, Palette } from 'lucide-vue-next'
import { useI18n } from '@/composables/useI18n'

export type SettingsPageKey =
  | 'general'
  | 'hotkeys'
  | 'capture'
  | 'windowScene'
  | 'floatingWindow'
  | 'webAppearance'

interface SettingsMenuItem {
  key: SettingsPageKey
  label: string
  icon: any
  description: string
}

defineProps<{
  activePage: SettingsPageKey
}>()

const emit = defineEmits<{
  (e: 'update:activePage', page: SettingsPageKey): void
}>()

const { t } = useI18n()

const settingsMenus: SettingsMenuItem[] = [
  {
    key: 'general',
    label: 'settings.layout.general.title',
    icon: Settings,
    description: 'settings.layout.general.description',
  },
  {
    key: 'hotkeys',
    label: 'settings.layout.hotkeys.title',
    icon: Keyboard,
    description: 'settings.layout.hotkeys.description',
  },
  {
    key: 'capture',
    label: 'settings.layout.capture.title',
    icon: Camera,
    description: 'settings.layout.capture.description',
  },
  {
    key: 'windowScene',
    label: 'settings.layout.windowScene.title',
    icon: Monitor,
    description: 'settings.layout.windowScene.description',
  },
  {
    key: 'floatingWindow',
    label: 'settings.layout.floatingWindow.title',
    icon: Menu,
    description: 'settings.layout.floatingWindow.description',
  },
  {
    key: 'webAppearance',
    label: 'settings.layout.webAppearance.title',
    icon: Palette,
    description: 'settings.layout.webAppearance.description',
  },
]

const handleMenuClick = (key: SettingsPageKey) => {
  emit('update:activePage', key)
}
</script>

<template>
  <div class="flex h-full w-48 flex-col border-r border-panel bg-muted/20 lg:w-56 2xl:w-64">
    <div class="h-full p-4">
      <nav class="flex-1">
        <div class="space-y-1">
          <div v-for="item in settingsMenus" :key="item.key" class="group">
            <button
              @click="handleMenuClick(item.key)"
              :class="
                cn(
                  'flex w-full items-center space-x-3 rounded-md px-4 py-3 transition-all duration-200',
                  'text-left focus-visible:ring-2 focus-visible:ring-sidebar-ring focus-visible:ring-offset-2 focus-visible:outline-none',
                  'hover:bg-accent hover:text-accent-foreground',
                  activePage === item.key
                    ? 'bg-accent font-medium text-accent-foreground'
                    : 'text-muted-foreground'
                )
              "
              :title="t(item.description)"
            >
              <component :is="item.icon" class="h-5 w-5 flex-shrink-0" stroke-width="1.8" />
              <div class="min-w-0 flex-1">
                <div class="text-sm font-medium">{{ t(item.label) }}</div>
              </div>
            </button>
          </div>
        </div>
      </nav>
    </div>
  </div>
</template>

// web_app/src/features/settings/components/settings-sidebar.tsx
import { cn } from '@/lib/utils'
import { Info, Settings, Zap } from 'lucide-react'
import type { SettingsSidebarItem } from '../types'
import { useSettingsStore } from '../store/settings-store'

// 侧边栏菜单项配置
const sidebarItems: SettingsSidebarItem[] = [
  {
    id: 'general',
    label: '常规',
    icon: Settings,
    description: '主题、语言、基础设置'
  },
  {
    id: 'advanced',
    label: '高级',
    icon: Zap,
    description: '调试、性能、实验性功能'
  },
  {
    id: 'about',
    label: '关于',
    icon: Info,
    description: '版本信息、许可证'
  }
]

export function SettingsSidebar() {
  const { currentPage, setCurrentPage } = useSettingsStore()

  return (
    <div className="w-64 bg-background border-r border-border flex flex-col">
      {/* 侧边栏标题 */}
      <div className="p-6 border-b border-border">
        <h2 className="text-lg font-semibold text-foreground">设置</h2>
        <p className="text-sm text-muted-foreground mt-1">
          管理应用程序首选项
        </p>
      </div>

      {/* 菜单项 */}
      <nav className="flex-1 p-4">
        <div className="space-y-2">
          {sidebarItems.map((item) => {
            const Icon = item.icon
            const isActive = currentPage === item.id

            return (
              <button
                key={item.id}
                onClick={() => setCurrentPage(item.id)}
                className={cn(
                  "w-full text-left p-3 rounded-lg transition-all duration-200",
                  "hover:bg-accent hover:text-accent-foreground",
                  "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
                  "group relative",
                  {
                    "bg-primary text-primary-foreground shadow-sm": isActive,
                    "text-muted-foreground hover:text-foreground": !isActive,
                  }
                )}
              >
                <div className="flex items-start space-x-3">
                  <Icon 
                    className={cn(
                      "h-5 w-5 mt-0.5 transition-colors",
                      {
                        "text-primary-foreground": isActive,
                        "text-muted-foreground group-hover:text-foreground": !isActive,
                      }
                    )} 
                  />
                  <div className="flex-1 min-w-0">
                    <div className={cn(
                      "font-medium text-sm transition-colors",
                      {
                        "text-primary-foreground": isActive,
                        "text-foreground": !isActive,
                      }
                    )}>
                      {item.label}
                    </div>
                    {item.description && (
                      <div className={cn(
                        "text-xs mt-1 transition-colors",
                        {
                          "text-primary-foreground/80": isActive,
                          "text-muted-foreground": !isActive,
                        }
                      )}>
                        {item.description}
                      </div>
                    )}
                  </div>
                </div>

                {/* 活跃指示器 */}
                {isActive && (
                  <div className="absolute left-0 top-0 bottom-0 w-2 bg-primary-foreground rounded-r-full" />
                )}
              </button>
            )
          })}
        </div>
      </nav>

      {/* 底部信息 */}
      <div className="p-4 border-t border-border">
        <div className="text-xs text-muted-foreground">
          SpinningMomo 设置面板
        </div>
      </div>
    </div>
  )
}
