// web/src/features/gallery/components/GalleryToolbar.vue
<template>
  <div class="flex items-center gap-3 bg-background p-4">
    <!-- 左侧：快速操作 -->
    <div class="flex items-center gap-2">
      <TooltipProvider>
        <Tooltip v-if="hasSelection">
          <TooltipTrigger as-child>
            <Button variant="ghost" size="sm" @click="$emit('deleteSelected')">
              <Trash2 class="h-4 w-4" />
              <span class="ml-1.5 hidden sm:inline">删除 ({{ selectedCount }})</span>
            </Button>
          </TooltipTrigger>
          <TooltipContent>
            <p>删除选中的 {{ selectedCount }} 项资产</p>
          </TooltipContent>
        </Tooltip>

        <Tooltip>
          <TooltipTrigger as-child>
            <Button variant="ghost" size="sm" @click="$emit('refresh')" :disabled="isLoading">
              <RefreshCw class="h-4 w-4" :class="{ 'animate-spin': isLoading }" />
            </Button>
          </TooltipTrigger>
          <TooltipContent>
            <p>重新加载图库资产</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    </div>

    <!-- 中间：搜索框 -->
    <div class="max-w-md min-w-[200px] flex-1">
      <div class="relative">
        <Search class="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input
          :model-value="searchQuery"
          @update:model-value="updateSearchQuery"
          placeholder="搜索资产名称..."
          class="pl-10"
        />
        <button
          v-if="searchQuery"
          class="absolute top-1/2 right-3 -translate-y-1/2 text-muted-foreground transition-colors hover:text-foreground"
          @click="clearSearch"
        >
          <X class="h-4 w-4" />
        </button>
      </div>
    </div>

    <!-- 右侧：筛选、排序、视图控制 -->
    <div class="flex items-center gap-2">
      <!-- 筛选与排序下拉菜单 -->
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger as-child>
            <div>
              <DropdownMenu>
                <DropdownMenuTrigger as-child>
                  <Button variant="ghost" size="sm">
                    <SlidersHorizontal class="h-4 w-4" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" class="w-56">
                  <!-- 类型筛选 -->
                  <DropdownMenuLabel>资产类型</DropdownMenuLabel>
                  <DropdownMenuRadioGroup
                    :model-value="filter.type || 'all'"
                    @update:model-value="onTypeFilterChange"
                  >
                    <DropdownMenuRadioItem value="all">全部类型</DropdownMenuRadioItem>
                    <DropdownMenuRadioItem value="photo">📷 照片</DropdownMenuRadioItem>
                    <DropdownMenuRadioItem value="video">🎥 视频</DropdownMenuRadioItem>
                    <DropdownMenuRadioItem value="live_photo">📸 实况</DropdownMenuRadioItem>
                  </DropdownMenuRadioGroup>

                  <DropdownMenuSeparator />

                  <!-- 排序方式 -->
                  <DropdownMenuLabel>排序方式</DropdownMenuLabel>
                  <DropdownMenuRadioGroup
                    :model-value="sortBy"
                    @update:model-value="onSortByChange"
                  >
                    <DropdownMenuRadioItem value="createdAt">📅 创建日期</DropdownMenuRadioItem>
                    <DropdownMenuRadioItem value="name">📝 名称</DropdownMenuRadioItem>
                    <DropdownMenuRadioItem value="size">📏 大小</DropdownMenuRadioItem>
                  </DropdownMenuRadioGroup>

                  <DropdownMenuSeparator />

                  <!-- 排序顺序 -->
                  <DropdownMenuItem @click="toggleSortOrder">
                    <ArrowUpDown class="mr-2 h-4 w-4" />
                    <span>{{ sortOrder === 'asc' ? '升序排列' : '降序排列' }}</span>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </TooltipTrigger>
          <TooltipContent>
            <p>筛选与排序</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>

      <!-- 视图设置（模式 + 大小调整） -->
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger as-child>
            <div>
              <Popover>
                <PopoverTrigger as-child>
                  <Button variant="ghost" size="sm">
                    <component :is="currentViewModeIcon" class="h-4 w-4" />
                  </Button>
                </PopoverTrigger>
                <PopoverContent align="end" class="w-72">
                  <div class="space-y-6">
                    <!-- 视图模式选择 -->
                    <div class="space-y-3">
                      <p class="text-sm font-medium">视图模式</p>
                      <div class="grid grid-cols-4 gap-2">
                        <Button
                          v-for="mode in viewModes"
                          :key="mode.value"
                          :variant="viewMode === mode.value ? 'default' : 'outline'"
                          size="sm"
                          class="flex h-auto flex-col items-center gap-1.5 py-3"
                          @click="setViewMode(mode.value)"
                        >
                          <component :is="mode.icon" class="h-5 w-5" />
                          <span class="text-xs">{{ mode.label }}</span>
                        </Button>
                      </div>
                    </div>

                    <!-- 分隔线 -->
                    <div class="border-t" />

                    <!-- 缩略图大小调整 -->
                    <div class="space-y-3">
                      <div class="flex items-center justify-between">
                        <p class="text-sm font-medium">缩略图大小</p>
                        <span class="text-sm text-muted-foreground">{{ viewSizeLabel }}</span>
                      </div>
                      <Slider
                        :model-value="[viewSize]"
                        @update:model-value="onViewSizeSliderChange"
                        :min="1"
                        :max="5"
                        :step="1"
                        class="w-full"
                      />
                      <div class="flex justify-between text-xs text-muted-foreground">
                        <span>超小</span>
                        <span>小</span>
                        <span>中</span>
                        <span>大</span>
                        <span>超大</span>
                      </div>
                    </div>
                  </div>
                </PopoverContent>
              </Popover>
            </div>
          </TooltipTrigger>
          <TooltipContent>
            <p>视图设置</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Slider } from '@/components/ui/slider'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
  Trash2,
  RefreshCw,
  Search,
  X,
  ArrowUpDown,
  Grid3x3,
  LayoutGrid,
  List,
  Rows3,
  SlidersHorizontal,
} from 'lucide-vue-next'
import { useGalleryView } from '../composables'
import type { ViewMode, SortBy, AssetType } from '../types'

// Props 定义
interface GalleryToolbarProps {
  isLoading?: boolean
  selectedCount?: number
}

const props = withDefaults(defineProps<GalleryToolbarProps>(), {
  isLoading: false,
  selectedCount: 0,
})

// Emits 定义
const emit = defineEmits<{
  refresh: []
  deleteSelected: []
}>()

// 使用视图管理逻辑
const galleryView = useGalleryView()

// 计算属性
const viewMode = computed(() => galleryView.viewMode.value)
const viewSize = computed(() => galleryView.viewSize.value)
const sortBy = computed(() => galleryView.sortBy.value)
const sortOrder = computed(() => galleryView.sortOrder.value)
const filter = computed(() => galleryView.filter.value)
const searchQuery = computed(() => filter.value.searchQuery || '')

const hasSelection = computed(() => props.selectedCount > 0)

// 视图大小标签映射
const viewSizeLabels: Record<number, string> = {
  1: '超小',
  2: '小',
  3: '中',
  4: '大',
  5: '超大',
}

const viewSizeLabel = computed(() => viewSizeLabels[viewSize.value] || '中')

// 视图模式选项
const viewModes = [
  { value: 'grid' as ViewMode, icon: Grid3x3, label: '网格' },
  { value: 'masonry' as ViewMode, icon: LayoutGrid, label: '瀑布流' },
  { value: 'list' as ViewMode, icon: List, label: '列表' },
  { value: 'adaptive' as ViewMode, icon: Rows3, label: '自适应' },
]

// 当前视图模式的图标
const currentViewModeIcon = computed(() => {
  const mode = viewModes.find((m) => m.value === viewMode.value)
  return mode?.icon || Grid3x3
})

// 方法
function updateSearchQuery(query: string | number) {
  galleryView.setSearchQuery(String(query))
}

function clearSearch() {
  galleryView.setSearchQuery('')
}

function onTypeFilterChange(value: string | number | bigint | Record<string, any> | null) {
  const stringValue = String(value || 'all')
  const type = stringValue === 'all' ? undefined : (stringValue as AssetType)
  galleryView.setTypeFilter(type)
}

function onSortByChange(value: string | number | bigint | Record<string, any> | null) {
  if (value) {
    const newSortBy = String(value) as SortBy
    galleryView.setSorting(newSortBy, sortOrder.value)
  }
}

function toggleSortOrder() {
  galleryView.toggleSortOrder()
}

function setViewMode(
  mode:
    | string
    | number
    | bigint
    | Record<string, any>
    | null
    | (string | number | bigint | Record<string, any> | null)[]
) {
  if (mode && typeof mode === 'string') {
    galleryView.setViewMode(mode as ViewMode)
  }
}

function onViewSizeSliderChange(value: number[] | undefined) {
  if (value && value.length > 0 && value[0] !== undefined) {
    galleryView.setViewSize(value[0])
  }
}
</script>

// web/src/features/gallery/components/GalleryToolbar.tsx
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Separator } from '@/components/ui/separator'
import { Badge } from '@/components/ui/badge'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
  DropdownMenuItem,
} from '@/components/ui/dropdown-menu'
import {
  Search,
  Grid3X3,
  Columns,
  List,
  SortAsc,
  SortDesc,
  RefreshCw,
  Plus,
  MoreVertical,
} from 'lucide-react'
import { useGalleryStore } from '@/lib/gallery/galleryStore'
import { useGalleryData } from '@/lib/gallery/hooks/useGalleryData'
import { useGalleryView, useGallerySelection } from '../hooks'
import { useTranslation } from '@/lib/i18n'
import { cn } from '@/lib/utils'

export function GalleryToolbar() {
  // 使用 gallery hooks
  const view = useGalleryView()
  const selection = useGallerySelection()
  const { reload } = useGalleryData()
  const { t } = useTranslation()

  // 从 store 获取必要的状态
  const { filter, sortBy, sortOrder, isLoading, totalCount, setFilter, setSorting } =
    useGalleryStore()

  // 视图模式选项
  const viewModes = [
    { id: 'masonry', icon: Columns, label: t('gallery.toolbar.viewMode.masonry') },
    { id: 'adaptive', icon: Grid3X3, label: t('gallery.toolbar.viewMode.adaptive') },
    { id: 'grid', icon: Grid3X3, label: t('gallery.toolbar.viewMode.grid') },
    { id: 'list', icon: List, label: t('gallery.toolbar.viewMode.list') },
  ] as const

  // 排序选项
  const sortOptions = [
    { id: 'created_at', label: t('gallery.toolbar.sortBy.createdAt') },
    { id: 'filename', label: t('gallery.toolbar.sortBy.filename') },
    { id: 'size', label: t('gallery.toolbar.sortBy.fileSize') },
  ] as const

  return (
    <div className='border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60'>
      <div className='flex items-center justify-between gap-4 p-4'>
        {/* 左侧：搜索和筛选 */}
        <div className='flex items-center gap-3'>
          {/* 搜索框 */}
          <div className='relative'>
            <Search className='absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-muted-foreground' />
            <Input
              placeholder={t('gallery.toolbar.searchPlaceholder')}
              className='w-64 pl-9'
              value={filter.search_query || ''}
              onChange={(e) => setFilter({ ...filter, search_query: e.target.value })}
            />
          </div>

          {/* 刷新按钮 */}
          <Button variant='outline' size='icon' onClick={reload} disabled={isLoading}>
            <RefreshCw className={cn('h-4 w-4', isLoading && 'animate-spin')} />
          </Button>

          <Separator orientation='vertical' className='h-6' />

          {/* 统计信息 */}
          <div className='flex items-center gap-2 text-sm text-muted-foreground'>
            <span>{t('gallery.toolbar.totalItems', { count: totalCount })}</span>
            {selection.hasSelection && (
              <>
                <Separator orientation='vertical' className='h-4' />
                <Badge variant='secondary' className='text-xs'>
                  {t('gallery.toolbar.selectedItems', { count: selection.selectedCount })}
                </Badge>
              </>
            )}
          </div>
        </div>

        {/* 右侧：视图控制 */}
        <div className='flex items-center gap-2'>
          {/* 排序控制 */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant='outline' size='sm' className='gap-2'>
                {sortOrder === 'asc' ? (
                  <SortAsc className='h-4 w-4' />
                ) : (
                  <SortDesc className='h-4 w-4' />
                )}
                {sortOptions.find((opt) => opt.id === sortBy)?.label}
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align='end' className='w-40'>
              {sortOptions.map((option) => (
                <DropdownMenuItem
                  key={option.id}
                  onClick={() => setSorting(option.id, sortOrder)}
                  className={cn(sortBy === option.id && 'bg-accent')}
                >
                  {option.label}
                </DropdownMenuItem>
              ))}
              <Separator className='my-1' />
              <DropdownMenuItem
                onClick={() => setSorting(sortBy, sortOrder === 'asc' ? 'desc' : 'asc')}
              >
                {sortOrder === 'asc'
                  ? t('gallery.toolbar.sortOrder.desc')
                  : t('gallery.toolbar.sortOrder.asc')}
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          <Separator orientation='vertical' className='h-6' />

          {/* 视图模式切换 */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant='outline' size='sm' className='gap-2'>
                {(() => {
                  const currentMode = viewModes.find((mode) => mode.id === view.viewConfig.mode)
                  const Icon = currentMode?.icon || Columns
                  return (
                    <>
                      <Icon className='h-4 w-4' />
                      <span className='hidden sm:inline'>{currentMode?.label}</span>
                    </>
                  )
                })()}
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align='end' className='w-40'>
              {viewModes.map((mode) => {
                const Icon = mode.icon
                const isActive = view.viewConfig.mode === mode.id

                return (
                  <DropdownMenuItem
                    key={mode.id}
                    onClick={() => view.switchViewMode(mode.id)}
                    className={cn(isActive && 'bg-accent')}
                  >
                    <Icon className='mr-2 h-4 w-4' />
                    {mode.label}
                  </DropdownMenuItem>
                )
              })}
            </DropdownMenuContent>
          </DropdownMenu>

          {/* 更多操作 */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant='outline' size='icon'>
                <MoreVertical className='h-4 w-4' />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align='end'>
              <DropdownMenuItem>
                <Plus className='mr-2 h-4 w-4' />
                {t('gallery.toolbar.actions.scanDirectory')}
              </DropdownMenuItem>
              <DropdownMenuItem>{t('gallery.toolbar.actions.importMedia')}</DropdownMenuItem>
              <Separator />
              <DropdownMenuItem>{t('gallery.toolbar.actions.exportSelected')}</DropdownMenuItem>
              <DropdownMenuItem>{t('gallery.toolbar.actions.cleanupThumbnails')}</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
    </div>
  )
}
