// web/src/features/settings/components/DraggablePresetList.vue

<script setup lang="ts">
import { ref, onUnmounted } from 'vue'
import { Switch } from '@/components/ui/switch'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { GripVertical, Plus, Trash2 } from 'lucide-vue-next'
import { useI18n } from '@/composables/useI18n'
import type { PresetItem } from '../types'

const props = defineProps<{
  items: PresetItem[]
  title: string
  description: string
  addPlaceholder: string
  validateCustom?: (value: string) => boolean
}>()

const emit = defineEmits<{
  (e: 'reorder', items: PresetItem[]): void
  (e: 'toggle', id: string, enabled: boolean): void
  (e: 'add', item: Omit<PresetItem, 'order'>): void
  (e: 'remove', id: string): void
}>()

const { t } = useI18n()
const isAdding = ref(false)
const newItemValue = ref('')

// --- Drag & Drop State ---
const draggingId = ref<string | null>(null)
const pressedId = ref<string | null>(null)
const pressedEl = ref<HTMLElement | null>(null)
const dragOffset = ref(0)
const dragStartY = ref(0)
const itemsContainer = ref<HTMLElement | null>(null)

// --- Helper Actions ---

const handleAddItem = () => {
    const value = newItemValue.value.trim()
    if (!value) return
    if (props.items.some(item => item.id === value)) return // Exists
    if (props.validateCustom && !props.validateCustom(value)) return // Invalid

    emit('add', { id: value, enabled: true })
    newItemValue.value = ''
    isAdding.value = false
}

const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Enter') handleAddItem()
    if (e.key === 'Escape') {
        isAdding.value = false
        newItemValue.value = ''
    }
}

// --- Drag & Drop Logic ---

const handlePointerDown = (id: string, event: PointerEvent) => {
    if (event.button !== 0) return
    const target = event.currentTarget as HTMLElement
    if (!target) return

    pressedId.value = id
    pressedEl.value = target.closest('.draggable-item') as HTMLElement
    dragStartY.value = event.clientY
    dragOffset.value = 0

    window.addEventListener('pointermove', handlePointerMove)
    window.addEventListener('pointerup', handlePointerUp)
    window.addEventListener('pointercancel', handlePointerUp)
}

const handlePointerMove = (event: PointerEvent) => {
     if (draggingId.value) {
        const currentY = event.clientY
        const deltaY = currentY - dragStartY.value
        dragOffset.value = deltaY

        if (Math.abs(deltaY) > 5) {
             checkSwap(currentY)
        }
        return
     }

     if (pressedId.value) {
         const currentY = event.clientY
         const moveDist = Math.abs(currentY - dragStartY.value)
         if (moveDist > 5) {
             draggingId.value = pressedId.value
             if (pressedEl.value) {
                 try {
                     pressedEl.value.setPointerCapture(event.pointerId)
                 } catch (e) { /* ignore */ }
             }
             dragOffset.value = currentY - dragStartY.value
         }
     }
}

const checkSwap = (cursorY: number) => {
    if (!draggingId.value || !itemsContainer.value) return
    
    const currentIndex = props.items.findIndex(item => item.id === draggingId.value)
    if (currentIndex === -1) return

    const itemElements = Array.from(itemsContainer.value.children) as HTMLElement[]

    if (currentIndex > 0) {
        const prevEl = itemElements[currentIndex - 1]
        if (prevEl) {
             const prevRect = prevEl.getBoundingClientRect()
             const prevCenter = prevRect.y + prevRect.height / 2
             if (cursorY < prevCenter) {
                 const newItems = [...props.items]
                 const moved = newItems.splice(currentIndex, 1)[0]
                 if (moved) {
                    newItems.splice(currentIndex - 1, 0, moved)
                    newItems.forEach((item, index) => item.order = index + 1)
                    emit('reorder', newItems)
                 }
                 dragStartY.value -= prevRect.height
                 dragOffset.value = cursorY - dragStartY.value
                 return
             }
        }
    }

    if (currentIndex < props.items.length - 1) {
        const nextEl = itemElements[currentIndex + 1]
        if (nextEl) {
            const nextRect = nextEl.getBoundingClientRect()
            const nextCenter = nextRect.y + nextRect.height / 2
            if (cursorY > nextCenter) {
                 const newItems = [...props.items]
                 const moved = newItems.splice(currentIndex, 1)[0]
                 if (moved) {
                    newItems.splice(currentIndex + 1, 0, moved)
                    newItems.forEach((item, index) => item.order = index + 1)
                    emit('reorder', newItems)
                 }
                 dragStartY.value += nextRect.height
                 dragOffset.value = cursorY - dragStartY.value
            }
        }
    }
}

const handlePointerUp = () => {
    draggingId.value = null
    pressedId.value = null
    pressedEl.value = null
    dragOffset.value = 0
    window.removeEventListener('pointermove', handlePointerMove)
    window.removeEventListener('pointerup', handlePointerUp)
    window.removeEventListener('pointercancel', handlePointerUp)
}

onUnmounted(() => {
    window.removeEventListener('pointermove', handlePointerMove)
    window.removeEventListener('pointerup', handlePointerUp)
    window.removeEventListener('pointercancel', handlePointerUp)
})
</script>

<template>
  <div class="space-y-4">
    <div>
      <h3 class="text-lg font-semibold text-foreground">{{ title }}</h3>
      <p class="mt-1 text-sm text-muted-foreground">{{ description }}</p>
    </div>

    <div class="rounded-lg border bg-card p-4 text-card-foreground shadow-sm">
        <div ref="itemsContainer" class="flex flex-col gap-1 relative">
            <TransitionGroup name="list">
                <div
                    v-for="item in items"
                    :key="item.id"
                    class="draggable-item flex items-center justify-between rounded-md p-3 transition-colors hover:bg-accent/50 group border border-transparent hover:border-primary/20 bg-card"
                    :style="{
                        transform: draggingId === item.id ? `translateY(${dragOffset}px)` : '',
                        zIndex: draggingId === item.id ? 50 : 'auto',
                        position: 'relative',
                    }"
                    :class="{
                        'cursor-grabbing': draggingId === item.id,
                        'select-none': draggingId === item.id
                    }"
                >
                    <div class="flex-1 pr-4 flex items-center gap-3">
                         <div 
                            class="cursor-grab hover:text-foreground text-muted-foreground active:cursor-grabbing p-1 -ml-1"
                            @pointerdown="handlePointerDown(item.id, $event)"
                         >
                            <GripVertical class="h-4 w-4" />
                         </div>
                         <Label class="text-sm font-medium text-foreground cursor-default pointer-events-none">
                            {{ item.id }}
                         </Label>
                    </div>
                    <div class="flex flex-shrink-0 items-center gap-2">
                        <Switch
                            :checked="item.enabled"
                            @update:checked="(v: boolean) => emit('toggle', item.id, v)"
                            @click.stop
                        />
                         <span class="min-w-[3rem] text-xs text-muted-foreground text-right">
                            {{ item.enabled ? t('settings.menu.status.visible') : t('settings.menu.status.hidden') }}
                         </span>
                         <Button 
                            variant="ghost" 
                            size="icon" 
                            class="h-8 w-8 text-destructive hover:text-destructive hover:bg-destructive/10" 
                            @click="emit('remove', item.id)"
                         >
                            <Trash2 class="h-4 w-4" />
                         </Button>
                    </div>
                </div>
            </TransitionGroup>
         </div>

         <!-- Add Item Section -->
        <div class="mt-4 pt-4 border-t">
           <div v-if="isAdding" class="flex items-center gap-2 rounded-md border border-primary bg-primary/5 p-3">
              <Input
                v-model="newItemValue"
                @keydown="handleKeyDown"
                :placeholder="addPlaceholder"
                class="flex-1"
                autofocus
              />
              <Button size="sm" @click="handleAddItem">
                {{ t('settings.menu.actions.add') }}
              </Button>
               <Button variant="ghost" size="sm" @click="() => { isAdding = false; newItemValue = '' }">
                {{ t('settings.menu.actions.cancel') }}
              </Button>
           </div>
           <Button
             v-else
             variant="outline"
             size="sm"
             class="w-full border-dashed hover:border-primary hover:text-primary"
             @click="isAdding = true"
           >
              <Plus class="mr-2 h-4 w-4" />
              {{ t('settings.menu.actions.addCustomItem') }}
           </Button>
        </div>

         <div v-if="items.length === 0 && !isAdding" class="flex items-center justify-center py-8 text-center text-muted-foreground text-sm">
            {{ t('settings.menu.status.noPresetItems') }}
        </div>
    </div>
  </div>
</template>

<style scoped>
.list-move {
  transition: transform 0.2s ease;
}

.draggable-item.cursor-grabbing {
    transition: none;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
}
</style>

// web/src/features/menu/components/DraggablePresetList.tsx
import React, { useState, useMemo } from 'react'
import { Switch } from '@/components/ui/switch'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { GripVertical, Plus, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import type { PresetItem } from '../types'

// 硬编码的预设项标签映射（比例和分辨率共用id作为label）
const getPresetItemLabel = (id: string): string => {
  return id
}

interface DraggablePresetListProps {
  items: PresetItem[]
  onReorder: (items: PresetItem[]) => void
  onToggle: (id: string, enabled: boolean) => void
  onAdd: (item: Omit<PresetItem, 'order'>) => void
  onRemove: (id: string) => void
  title: string
  description: string
  addPlaceholder: string
  validateCustom?: (value: string) => boolean
  className?: string
}

const DraggablePresetListComponent = React.memo<DraggablePresetListProps>(
  function DraggablePresetList({
    items,
    onReorder,
    onToggle,
    onAdd,
    onRemove,
    title,
    description,
    addPlaceholder,
    validateCustom,
    className = '',
  }) {
    const [draggedItem, setDraggedItem] = useState<string | null>(null)
    const [dragOverIndex, setDragOverIndex] = useState<number | null>(null)
    const [newItemValue, setNewItemValue] = useState('')
    const [isAdding, setIsAdding] = useState(false)

    const handleDragStart = (e: React.DragEvent, item: PresetItem) => {
      setDraggedItem(item.id)
      e.dataTransfer.effectAllowed = 'move'
      e.dataTransfer.setData('text/plain', item.id)
    }

    const handleDragOver = (e: React.DragEvent, index: number) => {
      e.preventDefault()
      e.dataTransfer.dropEffect = 'move'
      setDragOverIndex(index)
    }

    const handleDragLeave = () => {
      setDragOverIndex(null)
    }

    const handleDrop = (e: React.DragEvent, targetIndex: number) => {
      e.preventDefault()
      setDragOverIndex(null)

      if (!draggedItem) return

      const draggedIndex = items.findIndex((item) => item.id === draggedItem)
      if (draggedIndex === -1 || draggedIndex === targetIndex) return

      const newItems = [...items]
      const [removed] = newItems.splice(draggedIndex, 1)
      newItems.splice(targetIndex, 0, removed)

      // 重新计算order值
      const reorderedItems = newItems.map((item, index) => ({
        ...item,
        order: index + 1,
      }))

      onReorder(reorderedItems)
      setDraggedItem(null)
    }

    const handleDragEnd = () => {
      setDraggedItem(null)
      setDragOverIndex(null)
    }

    const handleAddItem = () => {
      const value = newItemValue.trim()
      if (!value) {
        toast.error('请输入有效值')
        return
      }

      // 检查是否已存在
      if (items.some((item) => item.id === value)) {
        toast.error('该项已存在')
        return
      }

      // 自定义验证
      if (validateCustom && !validateCustom(value)) {
        toast.error('格式不正确')
        return
      }

      const newItem: Omit<PresetItem, 'order'> = {
        id: value,
        enabled: true,
      }

      onAdd(newItem)
      setNewItemValue('')
      setIsAdding(false)
      toast.success('添加成功')
    }

    const handleRemove = (id: string) => {
      onRemove(id)
      toast.success('删除成功')
    }

    const handleKeyDown = (e: React.KeyboardEvent) => {
      if (e.key === 'Enter') {
        handleAddItem()
      } else if (e.key === 'Escape') {
        setIsAdding(false)
        setNewItemValue('')
      }
    }

    // 使用 useMemo 优化排序操作
    const sortedItems = useMemo(() => {
      return [...items].sort((a, b) => a.order - b.order)
    }, [items])

    return (
      <div className={`space-y-4 ${className}`}>
        <div className='pb-2'>
          <h3 className='text-lg font-semibold text-foreground'>{title}</h3>
          <p className='mt-1 text-sm text-muted-foreground'>{description}</p>
        </div>

        <div className='space-y-2 border-l-2 border-border pl-4'>
          {sortedItems.map((item, index) => (
            <PresetListItem
              key={item.id}
              item={item}
              index={index}
              draggedItem={draggedItem}
              dragOverIndex={dragOverIndex}
              onDragStart={handleDragStart}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              onDragEnd={handleDragEnd}
              onToggle={onToggle}
              onRemove={handleRemove}
            />
          ))}

          {/* 添加新项 */}
          {isAdding ? (
            <div className='flex items-center gap-2 rounded-lg border border-primary bg-primary/5 p-3'>
              <Input
                value={newItemValue}
                onChange={(e) => setNewItemValue(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder={addPlaceholder}
                className='flex-1'
                autoFocus
              />
              <Button size='sm' onClick={handleAddItem}>
                添加
              </Button>
              <Button
                variant='ghost'
                size='sm'
                onClick={() => {
                  setIsAdding(false)
                  setNewItemValue('')
                }}
              >
                取消
              </Button>
            </div>
          ) : (
            <Button
              variant='outline'
              size='sm'
              onClick={() => setIsAdding(true)}
              className='w-full border-dashed hover:border-primary hover:text-primary'
            >
              <Plus className='mr-2 h-4 w-4' />
              添加自定义项
            </Button>
          )}

          {sortedItems.length === 0 && !isAdding && (
            <div className='flex items-center justify-center py-8 text-center'>
              <p className='text-sm text-muted-foreground'>暂无预设项</p>
            </div>
          )}
        </div>
      </div>
    )
  }
)

// 单独的列表项组件，使用 React.memo 优化
const PresetListItem = React.memo<{
  item: PresetItem
  index: number
  draggedItem: string | null
  dragOverIndex: number | null
  onDragStart: (e: React.DragEvent, item: PresetItem) => void
  onDragOver: (e: React.DragEvent, index: number) => void
  onDragLeave: () => void
  onDrop: (e: React.DragEvent, targetIndex: number) => void
  onDragEnd: () => void
  onToggle: (id: string, enabled: boolean) => void
  onRemove: (id: string) => void
}>(function PresetListItem({
  item,
  index,
  draggedItem,
  dragOverIndex,
  onDragStart,
  onDragOver,
  onDragLeave,
  onDrop,
  onDragEnd,
  onToggle,
  onRemove,
}) {
  return (
    <div
      draggable
      onDragStart={(e) => onDragStart(e, item)}
      onDragOver={(e) => onDragOver(e, index)}
      onDragLeave={onDragLeave}
      onDrop={(e) => onDrop(e, index)}
      onDragEnd={onDragEnd}
      className={`flex cursor-move items-center justify-between rounded-lg border bg-card p-3 transition-all duration-200 ${draggedItem === item.id ? 'scale-95 opacity-50' : ''} ${dragOverIndex === index ? 'border-primary bg-primary/5' : 'border-border'} hover:border-primary/50 hover:bg-accent/50`}
    >
      <div className='flex flex-1 items-center gap-3'>
        <GripVertical className='h-4 w-4 text-muted-foreground' />
        <div className='flex-1'>
          <Label className='cursor-move text-sm font-medium text-foreground'>
            {getPresetItemLabel(item.id)}
          </Label>
        </div>
      </div>

      <div className='flex items-center gap-2'>
        <Switch
          checked={item.enabled}
          onCheckedChange={(enabled) => onToggle(item.id, enabled)}
          className='data-[state=checked]:bg-primary'
        />
        <span className='min-w-[3rem] text-xs text-muted-foreground'>
          {item.enabled ? '显示' : '隐藏'}
        </span>
        <Button
          variant='ghost'
          size='sm'
          onClick={() => onRemove(item.id)}
          className='h-8 w-8 p-0 text-destructive hover:bg-destructive/10 hover:text-destructive'
        >
          <Trash2 className='h-3 w-3' />
        </Button>
      </div>
    </div>
  )
})

export { DraggablePresetListComponent as DraggablePresetList }
