// web/src/features/settings/components/AppearanceContent.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { useSettingsStore } from '../store'
import { useAppearanceActions } from '../composables/useAppearanceActions'
import { useTheme } from '../composables/useTheme'
import { storeToRefs } from 'pinia'
import { Button } from '@/components/ui/button'
import { Slider } from '@/components/ui/slider'
import { Input } from '@/components/ui/input'
import {
  Item,
  ItemContent,
  ItemTitle,
  ItemDescription,
  ItemActions,
  ItemGroup,
} from '@/components/ui/item'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import ResetSettingsDialog from './ResetSettingsDialog.vue'
import { useI18n } from '@/composables/useI18n'
import type { WebThemeMode } from '../types'
import {
  SURFACE_OPACITY_RANGE,
  BACKGROUND_BLUR_RANGE,
  BACKGROUND_OPACITY_RANGE,
  OVERLAY_OPACITY_RANGE,
} from '../constants'

const store = useSettingsStore()
const { appSettings, error, isInitialized } = storeToRefs(store)
const { setTheme } = useTheme()
const {
  resetWebAppearanceSettings,
  updateBackgroundOpacity,
  updateBackgroundBlur,
  updateOverlayOpacity,
  updateOverlayStartColor,
  updateOverlayEndColor,
  updateSurfaceOpacity,
  handleBackgroundImageSelect,
  handleBackgroundImageRemove,
} = useAppearanceActions()
const { clearError } = store
const { t } = useI18n()

const themeOptions = [
  { value: 'light', label: t('settings.appearance.theme.light') },
  { value: 'dark', label: t('settings.appearance.theme.dark') },
  { value: 'system', label: t('settings.appearance.theme.system') },
]

const overlayStartHexInput = ref('#000000')
const overlayEndHexInput = ref('#000000')

watch(
  () => appSettings.value.ui.background.overlayStartColor,
  (value) => {
    overlayStartHexInput.value = value
  },
  { immediate: true }
)

watch(
  () => appSettings.value.ui.background.overlayEndColor,
  (value) => {
    overlayEndHexInput.value = value
  },
  { immediate: true }
)

const isValidHexColor = (value: string): boolean => /^#[0-9a-fA-F]{6}$/.test(value.trim())

const handleSurfaceOpacityChange = async (val: number[] | undefined) => {
  if (!val || val.length === 0) return
  try {
    await updateSurfaceOpacity(val[0]!)
  } catch (error) {
    console.error('Failed to update surface opacity:', error)
  }
}

const handleBackgroundOpacityChange = async (val: number[] | undefined) => {
  if (!val || val.length === 0) return
  try {
    await updateBackgroundOpacity(val[0]!)
  } catch (error) {
    console.error('Failed to update background opacity:', error)
  }
}

const handleBackgroundBlurAmountChange = async (val: number[] | undefined) => {
  if (!val || val.length === 0) return
  try {
    await updateBackgroundBlur(val[0]!)
  } catch (error) {
    console.error('Failed to update background blur amount:', error)
  }
}

const handleOverlayOpacityChange = async (val: number[] | undefined) => {
  if (!val || val.length === 0) return
  try {
    await updateOverlayOpacity(val[0]!)
  } catch (error) {
    console.error('Failed to update overlay opacity:', error)
  }
}

const handleOverlayStartColorPickerChange = async (value: string) => {
  if (!isValidHexColor(value)) return
  try {
    await updateOverlayStartColor(value.toUpperCase())
  } catch (error) {
    console.error('Failed to update overlay start color:', error)
  }
}

const handleOverlayEndColorPickerChange = async (value: string) => {
  if (!isValidHexColor(value)) return
  try {
    await updateOverlayEndColor(value.toUpperCase())
  } catch (error) {
    console.error('Failed to update overlay end color:', error)
  }
}

const commitOverlayStartHexInput = async () => {
  const normalized = overlayStartHexInput.value.trim().toUpperCase()
  if (!isValidHexColor(normalized)) {
    overlayStartHexInput.value = appSettings.value.ui.background.overlayStartColor
    return
  }
  try {
    await updateOverlayStartColor(normalized)
  } catch (error) {
    console.error('Failed to update overlay start color from hex:', error)
    overlayStartHexInput.value = appSettings.value.ui.background.overlayStartColor
  }
}

const commitOverlayEndHexInput = async () => {
  const normalized = overlayEndHexInput.value.trim().toUpperCase()
  if (!isValidHexColor(normalized)) {
    overlayEndHexInput.value = appSettings.value.ui.background.overlayEndColor
    return
  }
  try {
    await updateOverlayEndColor(normalized)
  } catch (error) {
    console.error('Failed to update overlay end color from hex:', error)
    overlayEndHexInput.value = appSettings.value.ui.background.overlayEndColor
  }
}

const handleThemeChange = async (themeMode: string) => {
  try {
    await setTheme(themeMode as WebThemeMode)
  } catch (error) {
    console.error('Failed to update theme:', error)
  }
}

const handleResetSettings = async () => {
  await resetWebAppearanceSettings()
}

const handleClearError = () => {
  clearError()
}
</script>

<template>
  <div v-if="!isInitialized" class="flex items-center justify-center p-6">
    <div class="text-center">
      <div
        class="mx-auto h-8 w-8 animate-spin rounded-full border-4 border-muted border-t-primary"
      ></div>
      <p class="mt-2 text-sm text-muted-foreground">{{ t('settings.webAppearance.loading') }}</p>
    </div>
  </div>

  <div v-else-if="error" class="flex items-center justify-center p-6">
    <div class="text-center">
      <p class="text-sm text-muted-foreground">{{ t('settings.webAppearance.error.title') }}</p>
      <p class="mt-1 text-sm text-red-500">{{ error }}</p>
      <Button variant="outline" size="sm" @click="handleClearError" class="mt-2">
        {{ t('settings.webAppearance.error.retry') }}
      </Button>
    </div>
  </div>

  <div v-else class="w-full">
    <div class="mb-6 flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-foreground">{{ t('settings.webAppearance.title') }}</h1>
        <p class="mt-1 text-muted-foreground">{{ t('settings.webAppearance.description') }}</p>
      </div>
      <ResetSettingsDialog
        :title="t('settings.webAppearance.reset.title')"
        :description="t('settings.webAppearance.reset.description')"
        @reset="handleResetSettings"
      />
    </div>

    <div class="space-y-8">
      <div class="space-y-4">
        <div>
          <h3 class="text-lg font-semibold text-foreground">
            {{ t('settings.appearance.background.title') }}
          </h3>
          <p class="mt-1 text-sm text-muted-foreground">
            {{ t('settings.appearance.background.description') }}
          </p>
        </div>

        <ItemGroup>
          <Item variant="surface" size="sm">
            <ItemContent>
              <ItemTitle>
                {{ t('settings.appearance.background.backgroundOpacity.label') }}
              </ItemTitle>
              <ItemDescription>
                {{ t('settings.appearance.background.backgroundOpacity.description') }}
              </ItemDescription>
            </ItemContent>
            <ItemActions>
              <div class="flex items-center gap-2">
                <Slider
                  :model-value="[appSettings.ui.background.backgroundOpacity]"
                  @update:model-value="handleBackgroundOpacityChange"
                  :min="BACKGROUND_OPACITY_RANGE.MIN"
                  :max="BACKGROUND_OPACITY_RANGE.MAX"
                  :step="BACKGROUND_OPACITY_RANGE.STEP"
                  class="w-36"
                />
                <span class="w-12 text-sm text-muted-foreground">
                  {{ (appSettings.ui.background.backgroundOpacity * 100).toFixed(0) }}%
                </span>
              </div>
            </ItemActions>
          </Item>

          <Item variant="surface" size="sm">
            <ItemContent>
              <ItemTitle>
                {{ t('settings.appearance.background.backgroundBlurAmount.label') }}
              </ItemTitle>
              <ItemDescription>
                {{ t('settings.appearance.background.backgroundBlurAmount.description') }}
              </ItemDescription>
            </ItemContent>
            <ItemActions>
              <div class="flex items-center gap-2">
                <Slider
                  :model-value="[appSettings.ui.background.backgroundBlurAmount]"
                  @update:model-value="handleBackgroundBlurAmountChange"
                  :min="BACKGROUND_BLUR_RANGE.MIN"
                  :max="BACKGROUND_BLUR_RANGE.MAX"
                  :step="BACKGROUND_BLUR_RANGE.STEP"
                  class="w-36"
                />
                <span class="w-12 text-sm text-muted-foreground">
                  {{ appSettings.ui.background.backgroundBlurAmount }}px
                </span>
              </div>
            </ItemActions>
          </Item>

          <Item variant="surface" size="sm">
            <ItemContent>
              <ItemTitle>
                {{ t('settings.appearance.background.overlayOpacity.label') }}
              </ItemTitle>
              <ItemDescription>
                {{ t('settings.appearance.background.overlayOpacity.description') }}
              </ItemDescription>
            </ItemContent>
            <ItemActions>
              <div class="flex items-center gap-2">
                <Slider
                  :model-value="[appSettings.ui.background.overlayOpacity]"
                  @update:model-value="handleOverlayOpacityChange"
                  :min="OVERLAY_OPACITY_RANGE.MIN"
                  :max="OVERLAY_OPACITY_RANGE.MAX"
                  :step="OVERLAY_OPACITY_RANGE.STEP"
                  class="w-36"
                />
                <span class="w-12 text-sm text-muted-foreground">
                  {{ (appSettings.ui.background.overlayOpacity * 100).toFixed(0) }}%
                </span>
              </div>
            </ItemActions>
          </Item>

          <Item variant="surface" size="sm">
            <ItemContent>
              <ItemTitle>
                {{ t('settings.appearance.background.overlayStartColor.label') }}
              </ItemTitle>
              <ItemDescription>
                {{ t('settings.appearance.background.overlayStartColor.description') }}
              </ItemDescription>
            </ItemContent>
            <ItemActions>
              <div class="flex items-center gap-2">
                <Input
                  type="color"
                  :model-value="appSettings.ui.background.overlayStartColor"
                  @update:model-value="(v) => handleOverlayStartColorPickerChange(v as string)"
                  class="h-9 w-12 p-1"
                />
                <Input
                  v-model="overlayStartHexInput"
                  class="w-28 font-mono uppercase"
                  placeholder="#000000"
                  @keydown.enter.prevent="commitOverlayStartHexInput"
                  @blur="commitOverlayStartHexInput"
                />
              </div>
            </ItemActions>
          </Item>

          <Item variant="surface" size="sm">
            <ItemContent>
              <ItemTitle>
                {{ t('settings.appearance.background.overlayEndColor.label') }}
              </ItemTitle>
              <ItemDescription>
                {{ t('settings.appearance.background.overlayEndColor.description') }}
              </ItemDescription>
            </ItemContent>
            <ItemActions>
              <div class="flex items-center gap-2">
                <Input
                  type="color"
                  :model-value="appSettings.ui.background.overlayEndColor"
                  @update:model-value="(v) => handleOverlayEndColorPickerChange(v as string)"
                  class="h-9 w-12 p-1"
                />
                <Input
                  v-model="overlayEndHexInput"
                  class="w-28 font-mono uppercase"
                  placeholder="#000000"
                  @keydown.enter.prevent="commitOverlayEndHexInput"
                  @blur="commitOverlayEndHexInput"
                />
              </div>
            </ItemActions>
          </Item>

          <Item variant="surface" size="sm">
            <ItemContent>
              <ItemTitle>
                {{ t('settings.appearance.background.surfaceOpacity.label') }}
              </ItemTitle>
              <ItemDescription>
                {{ t('settings.appearance.background.surfaceOpacity.description') }}
              </ItemDescription>
            </ItemContent>
            <ItemActions>
              <div class="flex items-center gap-2">
                <Slider
                  :model-value="[appSettings.ui.background.surfaceOpacity]"
                  @update:model-value="handleSurfaceOpacityChange"
                  :min="SURFACE_OPACITY_RANGE.MIN"
                  :max="SURFACE_OPACITY_RANGE.MAX"
                  :step="SURFACE_OPACITY_RANGE.STEP"
                  class="w-36"
                />
                <span class="w-12 text-sm text-muted-foreground">
                  {{ (appSettings.ui.background.surfaceOpacity * 100).toFixed(0) }}%
                </span>
              </div>
            </ItemActions>
          </Item>

          <Item variant="surface" size="sm">
            <ItemContent>
              <ItemTitle>
                {{ t('settings.appearance.background.image.label') }}
              </ItemTitle>
            </ItemContent>
            <ItemActions>
              <Button variant="outline" size="sm" @click="handleBackgroundImageSelect">
                {{ t('settings.appearance.background.image.selectButton') }}
              </Button>
              <Button
                variant="outline"
                size="sm"
                @click="handleBackgroundImageRemove"
                :disabled="appSettings.ui?.background?.type === 'none'"
              >
                {{ t('settings.appearance.background.image.removeButton') }}
              </Button>
            </ItemActions>
          </Item>
        </ItemGroup>
      </div>

      <div class="space-y-4">
        <div>
          <h3 class="text-lg font-semibold text-foreground">
            {{ t('settings.appearance.theme.title') }}
          </h3>
          <p class="mt-1 text-sm text-muted-foreground">
            {{ t('settings.appearance.theme.description') }}
          </p>
        </div>

        <Item variant="surface" size="sm">
          <ItemContent>
            <ItemTitle>
              {{ t('settings.appearance.theme.mode.label') }}
            </ItemTitle>
            <ItemDescription>
              {{ t('settings.appearance.theme.mode.description') }}
            </ItemDescription>
          </ItemContent>
          <ItemActions>
            <Select
              :model-value="appSettings.ui.webTheme.mode"
              @update:model-value="(v) => handleThemeChange(v as string)"
            >
              <SelectTrigger class="w-32">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem
                  v-for="option in themeOptions"
                  :key="option.value"
                  :value="option.value"
                >
                  {{ option.label }}
                </SelectItem>
              </SelectContent>
            </Select>
          </ItemActions>
        </Item>
      </div>
    </div>
  </div>
</template>

// web/src/features/settings/components/AppearanceContent.tsx
import { useState, useEffect } from 'react'
import { toast } from 'sonner'
import { useSettingsStore } from '@/lib/settings'
import { useAppearanceActions } from '@/features/settings/hooks/useAppearanceActions'
import { useWebSettingsStore } from '@/lib/web-settings'
import { useTheme } from 'next-themes'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Slider } from '@/components/ui/slider'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { ResetSettingsDialog } from './ResetSettingsDialog'
import { useTranslation } from '@/lib/i18n'
import type { AppWindowLayout } from '@/lib/settings/settingsTypes'

export function AppearanceContent() {
  const { t } = useTranslation()
  const { appSettings, error, isInitialized, clearError } = useSettingsStore()
  const { webSettings } = useWebSettingsStore()
  const {
    updateAppWindowLayout,
    resetAppearanceSettings,
    updateBackgroundOpacity,
    updateBackgroundBlur,
    handleBackgroundImageSelect,
    handleBackgroundImageRemove,
  } = useAppearanceActions()
  const { error: webSettingsError, initialize: initializeWebSettings } = useWebSettingsStore()
  const { theme, setTheme } = useTheme()

  // 当前布局设置状态
  const [layoutSettings, setLayoutSettings] = useState<AppWindowLayout>({
    baseItemHeight: 24,
    baseTitleHeight: 26,
    baseSeparatorHeight: 1,
    baseFontSize: 12,
    baseTextPadding: 12,
    baseIndicatorWidth: 3,
    baseRatioIndicatorWidth: 4,
    baseRatioColumnWidth: 60,
    baseResolutionColumnWidth: 120,
    baseSettingsColumnWidth: 120,
  })

  // 同步store中的布局设置到本地状态
  useEffect(() => {
    if (appSettings?.ui?.appWindowLayout) {
      setLayoutSettings(appSettings.ui.appWindowLayout)
    }
  }, [appSettings?.ui?.appWindowLayout])

  // 初始化web设置
  useEffect(() => {
    const initWebSettings = async () => {
      try {
        await initializeWebSettings()
      } catch (error) {
        console.error('Failed to initialize web settings:', error)
      }
    }
    initWebSettings()
  }, [initializeWebSettings])

  const handleInputChange = (field: keyof AppWindowLayout, value: string) => {
    const numValue = parseInt(value, 10)
    if (!isNaN(numValue) && numValue >= 0) {
      setLayoutSettings((prev) => ({
        ...prev,
        [field]: numValue,
      }))
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      e.preventDefault()
      // 触发失去焦点，从而触发保存
      e.currentTarget.blur()
    }
  }

  const handleInputBlur = async (field: keyof AppWindowLayout, value: string) => {
    const numValue = parseInt(value, 10)
    if (!isNaN(numValue) && numValue >= 0) {
      const newSettings = { ...layoutSettings, [field]: numValue }
      try {
        await updateAppWindowLayout(newSettings)
      } catch (error) {
        console.error('Failed to update layout settings:', error)
        toast.error(t('settings.appearance.layout.updateFailed'))
      }
    }
  }

  // Web设置处理函数
  const handleOpacityChange = async (opacity: number) => {
    try {
      await updateBackgroundOpacity(opacity)
    } catch (error) {
      console.error('Failed to update opacity:', error)
      toast.error(t('settings.appearance.background.updateFailed'))
    }
  }

  const handleBlurAmountChange = async (blurAmount: number) => {
    try {
      await updateBackgroundBlur(blurAmount)
    } catch (error) {
      console.error('Failed to update blur amount:', error)
      toast.error(t('settings.appearance.background.updateFailed'))
    }
  }

  const handleSelectBackgroundImage = async () => {
    try {
      await handleBackgroundImageSelect()
    } catch (error) {
      console.error('Failed to select background image:', error)
      toast.error(t('settings.appearance.background.selectFailed'))
    }
  }

  const handleRemoveBackgroundImage = async () => {
    try {
      await handleBackgroundImageRemove()
    } catch (error) {
      console.error('Failed to remove background image:', error)
      toast.error(t('settings.appearance.background.removeFailed'))
    }
  }

  // 主题选项
  const themeOptions = [
    { value: 'light', label: t('settings.appearance.theme.light') },
    { value: 'dark', label: t('settings.appearance.theme.dark') },
    { value: 'system', label: t('settings.appearance.theme.system') },
  ]

  // 主题切换处理
  const handleThemeChange = (themeMode: 'light' | 'dark' | 'system') => {
    setTheme(themeMode)
  }

  const handleResetSettings = async () => {
    await resetAppearanceSettings()
    toast.success(t('settings.appearance.reset.success'))
  }

  // 显示加载状态（仅在未初始化时）
  if (!isInitialized) {
    return (
      <div className='flex items-center justify-center p-6'>
        <div className='text-center'>
          <div className='mx-auto h-8 w-8 animate-spin rounded-full border-4 border-muted border-t-primary'></div>
          <p className='mt-2 text-sm text-muted-foreground'>{t('settings.appearance.loading')}</p>
        </div>
      </div>
    )
  }

  // 显示错误状态
  if (error || webSettingsError) {
    return (
      <div className='flex items-center justify-center p-6'>
        <div className='text-center'>
          <p className='text-sm text-muted-foreground'>{t('settings.appearance.error.title')}</p>
          <p className='mt-1 text-sm text-red-500'>{error || webSettingsError}</p>
          <Button variant='outline' size='sm' onClick={clearError} className='mt-2'>
            {t('settings.appearance.error.retry')}
          </Button>
        </div>
      </div>
    )
  }

  return (
    <div className='w-full'>
      {/* 页面标题 */}
      <div className='mb-6 flex items-center justify-between'>
        <div>
          <h1 className='text-2xl font-bold text-foreground'>{t('settings.appearance.title')}</h1>
          <p className='mt-1 text-muted-foreground'>{t('settings.appearance.description')}</p>
        </div>

        <ResetSettingsDialog
          title={t('settings.appearance.reset.title')}
          description={t('settings.appearance.reset.description')}
          onReset={handleResetSettings}
        />
      </div>

      <div className='space-y-8'>
        {/* 背景设置 */}
        <div className='space-y-4'>
          <div>
            <h3 className='text-lg font-semibold text-foreground'>
              {t('settings.appearance.background.title')}
            </h3>
            <p className='mt-1 text-sm text-muted-foreground'>
              {t('settings.appearance.background.description')}
            </p>
          </div>

          <div className='content-panel'>
            {/* 背景不透明度 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.background.opacity.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.background.opacity.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <div className='w-36'>
                  <Slider
                    value={[webSettings.ui.background.opacity]}
                    onValueChange={(value) => handleOpacityChange(value[0])}
                    min={0}
                    max={1}
                    step={0.1}
                    className='w-full'
                  />
                </div>
                <span className='w-12 text-sm text-muted-foreground'>
                  {(webSettings.ui.background.opacity * 100).toFixed(0)}%
                </span>
              </div>
            </div>

            {/* 背景模糊度 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.background.blurAmount.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.background.blurAmount.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <div className='w-36'>
                  <Slider
                    value={[webSettings.ui.background.blurAmount]}
                    onValueChange={(value) => handleBlurAmountChange(value[0])}
                    min={0}
                    max={200}
                    step={1}
                    className='w-full'
                  />
                </div>
                <span className='w-12 text-sm text-muted-foreground'>
                  {webSettings.ui.background.blurAmount}px
                </span>
              </div>
            </div>

            {/* 背景图片控制 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.background.image.label')}
                </Label>
              </div>
              <div className='flex flex-shrink-0 gap-2'>
                <Button variant='outline' size='sm' onClick={handleSelectBackgroundImage}>
                  {t('settings.appearance.background.image.selectButton')}
                </Button>
                <Button
                  variant='outline'
                  size='sm'
                  onClick={handleRemoveBackgroundImage}
                  disabled={webSettings.ui?.background?.type === 'none'}
                >
                  {t('settings.appearance.background.image.removeButton')}
                </Button>
              </div>
            </div>
          </div>
        </div>

        {/* 主题设置 */}
        <div className='space-y-4'>
          <div>
            <h3 className='text-lg font-semibold text-foreground'>
              {t('settings.appearance.theme.title')}
            </h3>
            <p className='mt-1 text-sm text-muted-foreground'>
              {t('settings.appearance.theme.description')}
            </p>
          </div>

          <div className='content-panel'>
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.theme.mode.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.theme.mode.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0'>
                <Select value={theme || 'system'} onValueChange={handleThemeChange}>
                  <SelectTrigger className='w-32'>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {themeOptions.map((option) => (
                      <SelectItem key={option.value} value={option.value}>
                        {option.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>
        </div>

        {/* 窗口外观参数 */}
        <div className='space-y-4'>
          <div>
            <h3 className='text-lg font-semibold text-foreground'>
              {t('settings.appearance.layout.title')}
            </h3>
            <p className='mt-1 text-sm text-muted-foreground'>
              {t('settings.appearance.layout.description')}
            </p>
          </div>

          <div className='content-panel'>
            {/* 基础项高度 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.layout.baseItemHeight.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.baseItemHeight.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <Input
                  type='number'
                  value={layoutSettings.baseItemHeight}
                  onChange={(e) => handleInputChange('baseItemHeight', e.target.value)}
                  onBlur={(e) => handleInputBlur('baseItemHeight', e.target.value)}
                  onKeyDown={handleKeyDown}
                  className='w-24'
                  min='0'
                />
                <span className='text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.unit')}
                </span>
              </div>
            </div>

            {/* 标题高度 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.layout.baseTitleHeight.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.baseTitleHeight.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <Input
                  type='number'
                  value={layoutSettings.baseTitleHeight}
                  onChange={(e) => handleInputChange('baseTitleHeight', e.target.value)}
                  onBlur={(e) => handleInputBlur('baseTitleHeight', e.target.value)}
                  onKeyDown={handleKeyDown}
                  className='w-24'
                  min='0'
                />
                <span className='text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.unit')}
                </span>
              </div>
            </div>

            {/* 分隔线高度 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.layout.baseSeparatorHeight.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.baseSeparatorHeight.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <Input
                  type='number'
                  value={layoutSettings.baseSeparatorHeight}
                  onChange={(e) => handleInputChange('baseSeparatorHeight', e.target.value)}
                  onBlur={(e) => handleInputBlur('baseSeparatorHeight', e.target.value)}
                  onKeyDown={handleKeyDown}
                  className='w-24'
                  min='0'
                />
                <span className='text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.unit')}
                </span>
              </div>
            </div>

            {/* 基础字体大小 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.layout.baseFontSize.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.baseFontSize.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <Input
                  type='number'
                  value={layoutSettings.baseFontSize}
                  onChange={(e) => handleInputChange('baseFontSize', e.target.value)}
                  onBlur={(e) => handleInputBlur('baseFontSize', e.target.value)}
                  onKeyDown={handleKeyDown}
                  className='w-24'
                  min='0'
                />
                <span className='text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.unit')}
                </span>
              </div>
            </div>

            {/* 文本内边距 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.layout.baseTextPadding.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.baseTextPadding.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <Input
                  type='number'
                  value={layoutSettings.baseTextPadding}
                  onChange={(e) => handleInputChange('baseTextPadding', e.target.value)}
                  onBlur={(e) => handleInputBlur('baseTextPadding', e.target.value)}
                  onKeyDown={handleKeyDown}
                  className='w-24'
                  min='0'
                />
                <span className='text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.unit')}
                </span>
              </div>
            </div>

            {/* 指示器宽度 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.layout.baseIndicatorWidth.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.baseIndicatorWidth.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <Input
                  type='number'
                  value={layoutSettings.baseIndicatorWidth}
                  onChange={(e) => handleInputChange('baseIndicatorWidth', e.target.value)}
                  onBlur={(e) => handleInputBlur('baseIndicatorWidth', e.target.value)}
                  onKeyDown={handleKeyDown}
                  className='w-24'
                  min='0'
                />
                <span className='text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.unit')}
                </span>
              </div>
            </div>

            {/* 比例指示器宽度 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.layout.baseRatioIndicatorWidth.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.baseRatioIndicatorWidth.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <Input
                  type='number'
                  value={layoutSettings.baseRatioIndicatorWidth}
                  onChange={(e) => handleInputChange('baseRatioIndicatorWidth', e.target.value)}
                  onBlur={(e) => handleInputBlur('baseRatioIndicatorWidth', e.target.value)}
                  onKeyDown={handleKeyDown}
                  className='w-24'
                  min='0'
                />
                <span className='text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.unit')}
                </span>
              </div>
            </div>

            {/* 比例列宽度 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.layout.baseRatioColumnWidth.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.baseRatioColumnWidth.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <Input
                  type='number'
                  value={layoutSettings.baseRatioColumnWidth}
                  onChange={(e) => handleInputChange('baseRatioColumnWidth', e.target.value)}
                  onBlur={(e) => handleInputBlur('baseRatioColumnWidth', e.target.value)}
                  onKeyDown={handleKeyDown}
                  className='w-24'
                  min='0'
                />
                <span className='text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.unit')}
                </span>
              </div>
            </div>

            {/* 分辨率列宽度 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.layout.baseResolutionColumnWidth.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.baseResolutionColumnWidth.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <Input
                  type='number'
                  value={layoutSettings.baseResolutionColumnWidth}
                  onChange={(e) => handleInputChange('baseResolutionColumnWidth', e.target.value)}
                  onBlur={(e) => handleInputBlur('baseResolutionColumnWidth', e.target.value)}
                  onKeyDown={handleKeyDown}
                  className='w-24'
                  min='0'
                />
                <span className='text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.unit')}
                </span>
              </div>
            </div>

            {/* 设置列宽度 */}
            <div className='flex items-center justify-between py-2'>
              <div className='flex-1 pr-4'>
                <Label className='text-sm font-medium text-foreground'>
                  {t('settings.appearance.layout.baseSettingsColumnWidth.label')}
                </Label>
                <p className='mt-1 text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.baseSettingsColumnWidth.description')}
                </p>
              </div>
              <div className='flex flex-shrink-0 items-center gap-2'>
                <Input
                  type='number'
                  value={layoutSettings.baseSettingsColumnWidth}
                  onChange={(e) => handleInputChange('baseSettingsColumnWidth', e.target.value)}
                  onBlur={(e) => handleInputBlur('baseSettingsColumnWidth', e.target.value)}
                  onKeyDown={handleKeyDown}
                  className='w-24'
                  min='0'
                />
                <span className='text-sm text-muted-foreground'>
                  {t('settings.appearance.layout.unit')}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
