// web/src/features/gallery/layout/GallerySidebar.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { useGalleryStore } from '../store'
import { useGallerySidebar, useGalleryData } from '../composables'
import FolderTreeItem from '../components/FolderTreeItem.vue'

const store = useGalleryStore()
const galleryData = useGalleryData()

const {
  folders,
  tags,
  sidebar,
  selectedFolder,
  selectedTag,
  loading,
  error,
  selectFolder,
  selectTag,
  selectAllMedia,
  addNewTag,
} = useGallerySidebar()

onMounted(() => {
  galleryData.loadFolderTree()
})

const totalCount = computed(() => store.foldersAssetTotalCount)
</script>

<template>
  <div class="flex h-full flex-col border-r bg-background">
    <!-- 标题栏 -->
    <div class="flex h-12 items-center justify-between border-b px-4">
      <h2 class="text-sm font-medium">资源库</h2>
      <Button variant="ghost" size="icon" class="h-7 w-7">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path
            d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"
          />
          <circle cx="12" cy="12" r="3" />
        </svg>
      </Button>
    </div>

    <!-- 导航菜单 -->
    <div class="flex-1 overflow-auto p-4">
      <!-- 所有媒体 -->
      <Button
        :variant="sidebar.activeSection === 'all' ? 'secondary' : 'ghost'"
        :class="['h-9 w-full justify-start gap-3', sidebar.activeSection === 'all' && 'bg-accent']"
        @click="selectAllMedia"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="flex-shrink-0"
        >
          <path
            d="m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72Z"
          />
          <path d="m14 7 3 3" />
          <path d="M5 6v4" />
          <path d="M19 14v4" />
          <path d="M10 2v2" />
          <path d="M7 8H3" />
          <path d="M21 16h-4" />
          <path d="M11 3H9" />
        </svg>
        <span class="flex-1 text-left">所有媒体</span>
        <span class="rounded bg-secondary px-1.5 py-0.5 text-xs">{{ totalCount }}</span>
      </Button>

      <!-- 文件夹区域 -->
      <div class="mt-4 space-y-2">
        <h3 class="px-2 text-xs font-medium tracking-wider text-muted-foreground uppercase">
          文件夹
        </h3>
        <!-- 加载状态 -->
        <div v-if="loading" class="px-2 text-xs text-muted-foreground">加载中...</div>
        <!-- 错误状态 -->
        <div v-else-if="error" class="px-2 text-xs text-destructive">
          {{ error }}
        </div>
        <!-- 文件夹树 -->
        <div v-else class="space-y-1">
          <FolderTreeItem
            v-for="folder in folders"
            :key="folder.id"
            :folder="folder"
            :selected-folder="selectedFolder"
            :depth="0"
            @select="selectFolder"
          />
        </div>
      </div>

      <Separator class="my-4" />

      <!-- 标签区域 -->
      <div class="space-y-2">
        <div class="flex items-center justify-between px-2">
          <h3 class="text-xs font-medium tracking-wider text-muted-foreground uppercase">标签</h3>
          <Button variant="ghost" size="icon" class="h-6 w-6" @click="addNewTag">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="12"
              height="12"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="M5 12h14" />
              <path d="M12 5v14" />
            </svg>
          </Button>
        </div>
        <div v-for="tag in tags" :key="tag.id">
          <Button
            :variant="selectedTag === tag.id ? 'secondary' : 'ghost'"
            :class="['h-8 w-full justify-start gap-2 px-2', selectedTag === tag.id && 'bg-accent']"
            @click="selectTag(tag.id, tag.name)"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="14"
              height="14"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="flex-shrink-0"
            >
              <path
                d="M12 2H2v10l9.29 9.29c.94.94 2.48.94 3.42 0l6.58-6.58c.94-.94.94-2.48 0-3.42L12 2Z"
              />
              <path d="M7 7h.01" />
            </svg>
            <span class="flex-1 text-left text-sm">{{ tag.name }}</span>
            <span class="rounded border px-1.5 py-0.5 text-xs">{{ tag.count }}</span>
          </Button>
        </div>
      </div>
    </div>

    <!-- 底部信息 -->
    <div class="border-t p-4">
      <div class="text-center text-xs text-muted-foreground">
        {{ totalCount > 0 ? `共 ${totalCount} 项` : '暂无项目' }}
      </div>
    </div>
  </div>
</template>

// web/src/features/gallery/layout/GallerySidebar.tsx
import { ScrollArea } from '@/components/ui/scroll-area'
import { Separator } from '@/components/ui/separator'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Images, Tag, Settings2, ChevronRight, FolderOpen, Plus } from 'lucide-react'
import { useGalleryStore } from '@/lib/gallery/galleryStore'
import { useGallerySidebar } from '../hooks'
import { useTranslation } from '@/lib/i18n'
import { cn } from '@/lib/utils'
import type { Folder } from '@/lib/gallery/mockData'
// 文件夹树项组件
function FolderTreeItem({
  folder,
  level = 0,
  isSelected,
  selectedFolder,
  onToggle,
  onSelect,
  isExpanded,
  checkExpanded,
}: {
  folder: Folder
  level?: number
  isSelected: boolean
  selectedFolder: string | null
  onToggle: (id: string) => void
  onSelect: (id: string, name: string) => void
  isExpanded: boolean
  checkExpanded: (id: string) => boolean
}) {
  const toggleExpanded = () => {
    onToggle(folder.id)
  }

  const handleSelect = () => {
    onSelect(folder.id, folder.name)
  }

  return (
    <div className='space-y-1'>
      <Button
        variant={isSelected ? 'secondary' : 'ghost'}
        className={cn('h-8 w-full justify-start gap-2 px-2', isSelected && 'bg-accent')}
        style={{ paddingLeft: `${8 + level * 16}px` }}
        onClick={handleSelect}
      >
        {folder.children && (
          <div
            className='flex-shrink-0 cursor-pointer'
            onClick={(e) => {
              e.stopPropagation()
              toggleExpanded()
            }}
          >
            <ChevronRight
              className={`h-3 w-3 transition-transform ${isExpanded ? 'rotate-90' : ''}`}
            />
          </div>
        )}
        <FolderOpen className='h-3 w-3 flex-shrink-0' />
        <span className='flex-1 text-left text-sm'>{folder.name}</span>
      </Button>

      {isExpanded && folder.children && (
        <div className='space-y-1'>
          {folder.children?.map((child: Folder) => (
            <FolderTreeItem
              key={child.id}
              folder={child}
              level={level + 1}
              isSelected={selectedFolder === child.id}
              selectedFolder={selectedFolder}
              onToggle={onToggle}
              onSelect={onSelect}
              isExpanded={checkExpanded(child.id)}
              checkExpanded={checkExpanded}
            />
          ))}
        </div>
      )}
    </div>
  )
}

export function GallerySidebar() {
  const { totalCount } = useGalleryStore()
  const { t } = useTranslation()

  // 使用 gallery sidebar hook
  const sidebarHook = useGallerySidebar({ useMockData: true })
  const {
    folders,
    tags,
    sidebar,
    selectedFolder,
    selectedTag,
    selectFolder,
    selectTag,
    selectAllMedia,
    toggleFolderExpanded,
    isFolderExpanded,
    addNewTag,
  } = sidebarHook

  return (
    <div className='flex h-full flex-col border-r bg-muted/10'>
      {/* 标题栏 */}
      <div className='flex h-12 items-center justify-between border-b px-4'>
        <h2 className='text-sm font-medium'>{t('gallery.sidebar.title')}</h2>
        <Button variant='ghost' size='icon' className='h-7 w-7'>
          <Settings2 className='h-4 w-4' />
        </Button>
      </div>

      {/* 导航菜单 */}
      <ScrollArea className='flex-1 p-4'>
        {/* 上面区域 - 媒体和文件夹 */}
        <div className='space-y-4'>
          {/* 所有媒体 */}
          <Button
            variant={sidebar.activeSection === 'all' ? 'secondary' : 'ghost'}
            className={cn(
              'h-9 w-full justify-start gap-3',
              sidebar.activeSection === 'all' && 'bg-accent'
            )}
            onClick={selectAllMedia}
          >
            <Images className='h-4 w-4 flex-shrink-0' />
            <span className='flex-1 text-left'>{t('gallery.sidebar.allItems')}</span>
            <Badge variant='secondary' className='px-1.5 py-0.5 text-xs'>
              {totalCount}
            </Badge>
          </Button>

          {/* 文件夹区域 */}
          <div className='space-y-2'>
            <h3 className='px-2 text-xs font-medium tracking-wider text-muted-foreground uppercase'>
              文件夹
            </h3>
            {folders.map((folder) => (
              <FolderTreeItem
                key={folder.id}
                folder={folder}
                isSelected={selectedFolder === folder.id}
                selectedFolder={selectedFolder}
                onToggle={toggleFolderExpanded}
                onSelect={selectFolder}
                isExpanded={isFolderExpanded(folder.id)}
                checkExpanded={isFolderExpanded}
              />
            ))}
          </div>
        </div>

        <Separator className='my-4' />

        {/* 下面区域 - 标签 */}
        <div className='space-y-2'>
          <div className='flex items-center justify-between px-2'>
            <h3 className='text-xs font-medium tracking-wider text-muted-foreground uppercase'>
              标签
            </h3>
            <Button variant='ghost' size='icon' className='h-6 w-6' onClick={addNewTag}>
              <Plus className='h-3 w-3' />
            </Button>
          </div>
          {tags.map((tag) => (
            <Button
              key={tag.id}
              variant={selectedTag === tag.id ? 'secondary' : 'ghost'}
              className={cn(
                'h-8 w-full justify-start gap-2 px-2',
                selectedTag === tag.id && 'bg-accent'
              )}
              onClick={() => selectTag(tag.id, tag.name)}
            >
              <Tag className='h-3 w-3 flex-shrink-0' />
              <span className='flex-1 text-left text-sm'>{tag.name}</span>
              <Badge variant='outline' className='px-1.5 py-0.5 text-xs'>
                {tag.count}
              </Badge>
            </Button>
          ))}
        </div>
      </ScrollArea>

      {/* 底部信息 */}
      <div className='border-t p-4'>
        <div className='text-center text-xs text-muted-foreground'>
          {totalCount > 0
            ? t('gallery.sidebar.itemCount', { count: totalCount })
            : t('gallery.sidebar.noItems')}
        </div>
      </div>
    </div>
  )
}
