// web/src/components/layout/ActivityBar.tsx
import {
  Sidebar,
  SidebarContent,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarGroup,
  SidebarGroupContent,
} from '@/components/ui/sidebar'
import { useNavigate, useLocation } from 'react-router'
import { Settings, Info, Home, Images } from 'lucide-react'

interface MenuItem {
  key?: string
  title?: string
  icon?: React.ElementType
  type?: 'divider'
}

const menuItems: MenuItem[] = [
  { title: '主页', key: 'home', icon: Home },
  { title: '图库', key: 'gallery', icon: Images },
  { title: '设置', key: 'settings', icon: Settings },
  { type: 'divider' },
  { title: '关于', key: 'about', icon: Info },
]

export function ActivityBar() {
  const navigate = useNavigate()
  const location = useLocation()
  const activeKey = location.pathname.split('/')[1] || 'home'

  const handleMenuSelect = (key: string) => {
    navigate(`/${key}`)
  }

  return (
    <Sidebar collapsible='none' className='w-14 bg-transparent pt-2'>
      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupContent className='px-0'>
            <SidebarMenu>
              {menuItems.map((item, index) =>
                item.type === 'divider' ? (
                  <div key={`divider-${index}`} className='mx-2 my-3'></div>
                ) : (
                  <SidebarMenuItem key={item.key}>
                    <SidebarMenuButton
                      tooltip={{
                        children: item.title,
                        hidden: false,
                      }}
                      isActive={activeKey === item.key}
                      onClick={() => item.key && handleMenuSelect(item.key)}
                      className='h-10 w-10 [&>svg]:mx-auto [&>svg]:h-5 [&>svg]:w-5'
                    >
                      {item.icon && <item.icon strokeWidth={1.8} />}
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                )
              )}
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>
    </Sidebar>
  )
}

// web/src/components/layout/ActivityBar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Home, Images, Settings, Info } from 'lucide-vue-next'
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
} from '@/components/ui/sidebar'

interface MenuItem {
  key: string
  title: string
  icon: any
}

const menuItems: (MenuItem | { type: 'divider' })[] = [
  { title: '主页', key: 'home', icon: Home },
  { title: '图库', key: 'gallery', icon: Images },
  { title: '设置', key: 'settings', icon: Settings },
  { type: 'divider' },
  { title: '关于', key: 'about', icon: Info },
]

const router = useRouter()
const route = useRoute()

const activeKey = computed(() => {
  const firstSegment = route.path.split('/')[1]
  return firstSegment || 'home'
})

const handleMenuSelect = (key: string) => {
  router.push(`/${key}`)
}
</script>

<template>
  <Sidebar collapsible="none" class="w-14 border-r border-panel pt-2">
    <SidebarContent>
      <SidebarGroup>
        <SidebarGroupContent class="px-0">
          <SidebarMenu>
            <template
              v-for="(item, index) in menuItems"
              :key="'key' in item ? item.key : `divider-${index}`"
            >
              <!-- Divider -->
              <div v-if="'type' in item && item.type === 'divider'" class="mx-2 my-3" />

              <!-- Menu Item -->
              <SidebarMenuItem v-else-if="'key' in item">
                <SidebarMenuButton
                  :tooltip="item.title"
                  :is-active="activeKey === item.key"
                  @click="handleMenuSelect(item.key)"
                  class="h-10 w-10 [&>svg]:mx-auto [&>svg]:h-5 [&>svg]:w-5"
                >
                  <component :is="item.icon" :stroke-width="1.8" />
                </SidebarMenuButton>
              </SidebarMenuItem>
            </template>
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>
    </SidebarContent>
  </Sidebar>
</template>
