// web/src/components/layout/AppLayout.vue
<script setup lang="ts">
import { useRoute } from 'vue-router'
import { isWebView } from '@/core/env'
import { SidebarProvider } from '@/components/ui/sidebar'
import { Toaster } from '@/components/ui/sonner'
import ActivityBar from './ActivityBar.vue'
import AppHeader from './AppHeader.vue'
import ContentArea from './ContentArea.vue'
import 'vue-sonner/style.css'

const route = useRoute()
const showHeader = isWebView()
const isHome = () => route.name === 'home'
</script>

<template>
  <SidebarProvider>
    <div class="relative h-screen w-screen overflow-hidden bg-transparent">
      <div class="pointer-events-none absolute inset-0 z-0">
        <div class="app-background-image absolute inset-0" />
        <div
          class="app-background-overlay absolute inset-0"
          :style="isHome() ? { opacity: 0 } : undefined"
        />
      </div>

      <div class="relative z-10 flex h-full w-full flex-row">
        <!-- 左侧 ActivityBar -->
        <ActivityBar />

        <!-- 右侧：Header + 主内容区 -->
        <div
          class="relative flex min-h-0 flex-1 flex-col overflow-hidden text-foreground"
          :class="[
            !isHome() && 'app-surface',
            showHeader ? 'rounded-lg' : 'rounded-tr-lg rounded-br-lg rounded-bl-lg',
          ]"
        >
          <!-- 窗口控制栏（仅 WebView 环境下显示，位于主内容区上方） -->
          <AppHeader v-if="showHeader" />
          <!-- 主内容区域 -->
          <div class="relative z-10 min-h-0 flex-1 overflow-auto">
            <ContentArea />
          </div>
        </div>
      </div>
    </div>

    <!-- Toast 通知 -->
    <Toaster position="bottom-right" richColors closeButton />
  </SidebarProvider>
</template>

// web/src/components/layout/AppLayout.tsx
import { ActivityBar } from './ActivityBar'
import { ContentArea } from './ContentArea'
import { Header } from './Header'
import { Toaster } from '@/components/ui/sonner'
import { isWebView } from '@/lib/environment'
import { useLocation } from 'react-router'

export default function AppLayout() {
  const showHeader = isWebView()
  const location = useLocation()
  const isHomePage = location.pathname === '/' || location.pathname.startsWith('/home')

  return (
    <>
      {/* Background Layer */}
      <div
        className='fixed inset-0 z-[-2] bg-cover bg-center bg-no-repeat'
        style={{
          backgroundImage: "url('http://localhost:8080/2025_03_30_02_33_09_3140045.jpeg')",
        }}
      />

      {/* Glass Overlay Layer */}
      <div
        className={`fixed inset-0 z-[-1] transition-opacity duration-300 ${
          isHomePage ? 'opacity-0' : 'opacity-100'
        }`}
        style={{
          backdropFilter: 'blur(60px)',
          background: 'rgba(255, 255, 255, 0.9)',
        }}
      />

      <div className='relative flex h-screen w-screen flex-col text-foreground'>
        {showHeader && <Header />}

        <div className='flex flex-1 overflow-hidden'>
          <ActivityBar />

          {/* Main Layout Area (Content) */}
          <div className='flex flex-1 overflow-hidden'>
            <ContentArea />
          </div>
        </div>
      </div>
      <Toaster />
    </>
  )
}
